<!-- Page header -->
<div class="page-header page-header-default">
    <div class="page-header-content">
        <div class="page-title">
            <h6><i class="icon-home2 position-left"></i> <span class="text-semibold"><a href="#">Trang chủ</a> / Sản phẩm</span></h6>
        </div>
    </div>
</div>
<!-- /page header -->



<div class="content">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">Danh sách sản phẩm</h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>

        <table class="table datatable-basic table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tên</th>
                    <th>Nhóm SP</th>
                    <th>Loại SP</th>
                    <th>Xuất xứ</th>
                    
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->data as $row) {
                    ?>
                    <tr>
                        <td><a href="#">#<?= $row['id_sanpham'] ?></a></td>
                        <td><?= $row['tensanpham'] ?></td>
                        <td><?= $row['tennhomsanpham'] ?></td>
                        <td><?= $row['tenloaisanpham'] ?></td>
                        <td><?= $row['xuatxu'] ?></td>
                        <td class="text-center">
                            <ul class="icons-list">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-menu9"></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="#"><i class="icon-file-pdf"></i>Sửa sản phẩm</a></li>
                                        <li><a href="#"><i class="icon-file-excel"></i>Xóa sản phẩm</a></li>

                                    </ul>
                                </li>
                            </ul>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>