<!-- Page header -->
<div class="page-header page-header-default">
    <div class="page-header-content">
        <div class="page-title">
            <h6><i class="icon-home2 position-left"></i> <span class="text-semibold"><a href="#">Trang chủ</a> / Người dùng</span></h6>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">Danh sách người dùng</h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>



        <table class="table datatable-selection-single">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tài khoản</th>
                    <th>Họ tên</th>
                    <th>Địa chỉ</th>
                    <th>Quyền truy cập</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->table as $row) {
                    echo '<td><a href="#">#' . $row['id_nguoidung'] . '</a></td>';
                    echo '<td>' . $row['taikhoan'] . '</td>';
                    echo '<td>' . $row['ho'] . ' ' . $row['tendem'] . ' ' . $row['ten'] . '</td>';
                    echo '<td>' . $row['diachi'] . '</td>';
//                        echo '<td>'.$row['quyentruycap'].'</td>';
                    switch ($row['quyentruycap']) {
                        case 1:
                            echo '<td>Người dùng</td>';
                            break;
                        case 2:
                            echo '<td>Quản lý</td>';
                            break;
                        case 3:
                            echo '<td>Admin</td>';
                            break;
                        default :
                            echo '<td>null</td>';
                    }
                    echo '<td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-menu9"></i>
                                </a>

                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="'.$this->url('admin/usertable',['action' =>'edit']).'?id='.$row['id_nguoidung'].'"><i class="glyphicon glyphicon-edit"></i> Chỉnh sửa</a></li>
                                    <li><a id="delete"><i class="glyphicon glyphicon-remove"></i> Xóa</a></li>
                                    
                                </ul>
                            </li>
                        </ul>
                    </td>';
                }
                ?>

            </tbody>
        </table>
    </div>
</div>