<!-- Page header -->
<div class="page-header page-header-default">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-home2 position-left"></i> <span class="text-semibold"><a href="#">Home</a></span></h4>
        </div>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">

    <!-- Main charts -->
    Biểu đồ thống kê truy cập</br>
    Biểu đồ thống kê doanh thu
    <!-- /main charts -->


    <!-- Dashboard content -->
    <div class="row">
        <div class="col-lg-12">

            <!-- Quick stats boxes -->
            <div class="row">
                <div class="col-lg-4">

                    <!-- Members online -->
                    <div class="panel bg-teal-400">
                        <div class="panel-body">
                            <div class="heading-elements">
                                <span class="heading-text badge bg-teal-800">+53,6%</span>
                            </div>

                            <h3 class="no-margin"><?= $this->songuoidangkymoi ?> Thành viên mới</h3>
                            Thành viên
                            <div class="text-muted text-size-small"><?= $this->songuoidung ?></div>
                        </div>

                        <div class="container-fluid">
                            <div id="members-online"></div>
                        </div>
                    </div>
                    <!-- /members online -->

                </div>

                <div class="col-lg-4">

                    <!-- Current server load -->
                    <div class="panel bg-pink-400">
                        <div class="panel-body">
                            <div class="heading-elements">
                                <ul class="icons-list">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cog3"></i> <span class="caret"></span></a>
                                        <ul class="dropdown-menu dropdown-menu-right">
                                            <li><a href="#"><i class="icon-sync"></i>Xem toàn bộ đơn hàng</a></li>
                                            <li><a href="#"><i class="icon-list-unordered"></i>Xem đơn hàng mới nhận</a></li>
                                            <li><a href="#"><i class="icon-pie5"></i>Làm mới</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>

                            <h3 class="no-margin"><?= $this->sodonhangmoi ?> Đơn hàng mới</h3>
                            Tổng số đơn hàng đã nhận
                            <div class="text-muted text-size-small"><?= $this->sodonhang ?> Đơn</div>
                        </div>

                        <div id="server-load"></div>
                    </div>
                    <!-- /current server load -->

                </div>

                <div class="col-lg-4">

                    <!-- Today's revenue -->
                    <div class="panel bg-blue-400">
                        <div class="panel-body">
                            <div class="heading-elements">
                                <ul class="icons-list">
                                    <li><a data-action="reload"></a></li>
                                </ul>
                            </div>

                            <h3 class="no-margin"><?= $this->sosanphammoi ?> Sản phẩm mới</h3>
                            Tất cả sản phẩm
                            <div class="text-muted text-size-small"><?= $this->sosanpham ?></div>
                        </div>

                        <div id="today-revenue"></div>
                    </div>
                    <!-- /today's revenue -->

                </div>
            </div>
            <!-- /quick stats boxes -->


            <!-- Support tickets -->
            <div class="panel panel-flat">
                

                <div class="table-responsive">
                    <table class="table text-nowrap">
                        <thead>
                            <tr>
                                <th style="width: 50px">Thời gian</th>
                                <th style="width: 300px;">Người đặt</th>
                                <th>Mã đơn hàng</th>
                                <th class="text-center" style="width: 20px;"><i class="icon-arrow-down12"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            
                                <?php
                                
                                    foreach ($this->donhangmoi as $row)
                                    {
                                        if(isset($row))
                                        {
                                            echo '<tr>';
                                            echo '<td class="text-center">
                                    <h7 class="no-margin">'.$row['ngaydatdonhang'].'</h7>
                                </td>';
                                            echo '<td>
                                    <div class="media-body">
                                        <a href="#" class="display-inline-block text-default text-semibold letter-icon-title">'.$row['ho'].' '.$row['ten'].'</a>
                                            
                                        
                                    </div>
                                </td>';
                                            echo '<td>
                                    <a href="#" class="text-default display-inline-block">
                                        <span class="text-semibold">[#'.$row['id_donhang'].'] Xem chi tiết đơn hàng</span>
                                        
                                    </a>
                                </td>';
                                            echo '<td class="text-center">
                                    <ul class="icons-list">
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu7"></i></a>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                <li><a href="#"><i class="icon-undo"></i> Quick reply</a></li>
                                                <li><a href="#"><i class="icon-history"></i> Full history</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#"><i class="icon-checkmark3 text-success"></i> Resolve issue</a></li>
                                                <li><a href="#"><i class="icon-cross2 text-danger"></i> Close issue</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </td>';
                                            echo '</tr>';
                                        }
                                    }
                                ?>
                            
                            <tr>
                                <td class="text-center">
                                    <h6 class="no-margin">12 <small class="display-block text-size-small no-margin">#</small></h6>
                                </td>
                                <td>
                                    <div class="media-left media-middle">
                                        <a href="#" class="btn bg-teal-400 btn-rounded btn-icon btn-xs">
                                            <span class="letter-icon"></span>
                                        </a>
                                    </div>

                                    <div class="media-body">
                                        <a href="#" class="display-inline-block text-default text-semibold letter-icon-title">Annabelle Doney</a>
                                        <div class="text-muted text-size-small"><span class="status-mark border-blue position-left"></span> Active</div>
                                    </div>
                                </td>
                                <td>
                                    <a href="#" class="text-default display-inline-block">
                                        <span class="text-semibold">[#1183] Xem chi tiết đơn hàng</span>
                                        <span class="display-block text-muted">Chrome fixed the bug several versions ago, thus rendering this...</span>
                                    </a>
                                </td>
                                <td class="text-center">
                                    <ul class="icons-list">
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu7"></i></a>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                <li><a href="#"><i class="icon-undo"></i> Quick reply</a></li>
                                                <li><a href="#"><i class="icon-history"></i> Full history</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#"><i class="icon-checkmark3 text-success"></i> Resolve issue</a></li>
                                                <li><a href="#"><i class="icon-cross2 text-danger"></i> Close issue</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </td>
                            </tr>

                            <tr>
                                <td class="text-center">
                                    <h6 class="no-margin">16 <small class="display-block text-size-small no-margin">hours</small></h6>
                                </td>
                                <td>
                                    <div class="media-left media-middle">
                                        <a href="#"><img src="assets/images/placeholder.jpg" class="img-circle img-xs" alt=""></a>
                                    </div>

                                    <div class="media-body">
                                        <a href="#" class="display-inline-block text-default text-semibold letter-icon-title">Chris Macintyre</a>
                                        <div class="text-muted text-size-small"><span class="status-mark border-blue position-left"></span> Active</div>
                                    </div>
                                </td>
                                <td>
                                    <a href="#" class="text-default display-inline-block">
                                        <span class="text-semibold">[#1249] Vertically center carousel controls</span>
                                        <span class="display-block text-muted">Try any carousel control and reduce the screen width below...</span>
                                    </a>
                                </td>
                                <td class="text-center">
                                    <ul class="icons-list">
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu7"></i></a>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                <li><a href="#"><i class="icon-undo"></i> Quick reply</a></li>
                                                <li><a href="#"><i class="icon-history"></i> Full history</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#"><i class="icon-checkmark3 text-success"></i> Resolve issue</a></li>
                                                <li><a href="#"><i class="icon-cross2 text-danger"></i> Close issue</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </td>
                            </tr>

                            <tr>
                                <td class="text-center">
                                    <h6 class="no-margin">20 <small class="display-block text-size-small no-margin">hours</small></h6>
                                </td>
                                <td>
                                    <div class="media-left media-middle">
                                        <a href="#" class="btn bg-blue btn-rounded btn-icon btn-xs">
                                            <span class="letter-icon"></span>
                                        </a>
                                    </div>

                                    <div class="media-body">
                                        <a href="#" class="display-inline-block text-default text-semibold letter-icon-title">Robert Hauber</a>
                                        <div class="text-muted text-size-small"><span class="status-mark border-blue position-left"></span> Active</div>
                                    </div>
                                </td>
                                <td>
                                    <a href="#" class="text-default display-inline-block">
                                        <span class="text-semibold">[#1254] Inaccurate small pagination height</span>
                                        <span class="display-block text-muted">The height of pagination elements is not consistent with...</span>
                                    </a>
                                </td>
                                <td class="text-center">
                                    <ul class="icons-list">
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu7"></i></a>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                <li><a href="#"><i class="icon-undo"></i> Quick reply</a></li>
                                                <li><a href="#"><i class="icon-history"></i> Full history</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#"><i class="icon-checkmark3 text-success"></i> Resolve issue</a></li>
                                                <li><a href="#"><i class="icon-cross2 text-danger"></i> Close issue</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </td>
                            </tr>

                            <tr>
                                <td class="text-center">
                                    <h6 class="no-margin">40 <small class="display-block text-size-small no-margin">hours</small></h6>
                                </td>
                                <td>
                                    <div class="media-left media-middle">
                                        <a href="#" class="btn bg-warning-400 btn-rounded btn-icon btn-xs">
                                            <span class="letter-icon"></span>
                                        </a>
                                    </div>

                                    <div class="media-body">
                                        <a href="#" class="display-inline-block text-default text-semibold letter-icon-title">Dex Sponheim</a>
                                        <div class="text-muted text-size-small"><span class="status-mark border-blue position-left"></span> Active</div>
                                    </div>
                                </td>
                                <td>
                                    <a href="#" class="text-default display-inline-block">
                                        <span class="text-semibold">[#1184] Round grid column gutter operations</span>
                                        <span class="display-block text-muted">Left rounds up, right rounds down. should keep everything...</span>
                                    </a>
                                </td>
                                <td class="text-center">
                                    <ul class="icons-list">
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu7"></i></a>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                <li><a href="#"><i class="icon-undo"></i> Quick reply</a></li>
                                                <li><a href="#"><i class="icon-history"></i> Full history</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#"><i class="icon-checkmark3 text-success"></i> Resolve issue</a></li>
                                                <li><a href="#"><i class="icon-cross2 text-danger"></i> Close issue</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /support tickets -->

        </div>
    </div>
    <!-- /dashboard content -->


    <!-- Footer -->
    <div class="footer text-muted">
        &copy; 2015. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
    </div>
    <!-- /footer -->

</div>
<!-- /content area -->